### ISSUE TITLE
ValueError: negative dimensions are not allowed in object_recognition.py

### ISSUE THREAD

**Issue by redhat12345** [wzell/mann#1]
All code are ok in PC, but when I run the following code its getting the error. Can you help me to fix it please? Keras version is 1.1.0.

(keras_python2) redhat@12:~/mann$ python object_recognition.py

Creating/Loading image representations via AlexNet model...
/home/redhat/keras_python2/local/lib/python2.7/site-packages/keras/backend/theano_backend.py:1282: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  mode='max')
/home/redhat/keras_python2/local/lib/python2.7/site-packages/keras/backend/theano_backend.py:1282: UserWarning: DEPRECATION: the 'st' parameter is not going to exist anymore as it is going to be replaced by the parameter 'stride'.
  mode='max')
/home/redhat/keras_python2/local/lib/python2.7/site-packages/keras/backend/theano_backend.py:1282: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
  mode='max')
Traceback (most recent call last):
  File "object_recognition.py", line 81, in <module>
    'amazon', N_IMAGES_AM)
  File "/home/redhat/mann/models/mann_object_recognition.py", line 186, in create_img_repr_alexnet
    an = self.AlexNet(weights_file)
  File "/home/redhat/mann/models/mann_object_recognition.py", line 448, in AlexNet
    dense_1 = Dense(4096, activation='relu', name='dense_1')(dense_1)
  File "/home/mahfuj/keras_python2/local/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/redhat/keras_python2/local/lib/python2.7/site-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/home/redhat/keras_python2/local/lib/python2.7/site-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/home/redhat/keras_python2/local/lib/python2.7/site-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/home/redhat/keras_python2/local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 140, in random_uniform_variable
    return variable(np.random.uniform(low=low, high=high, size=shape),
  File "mtrand.pyx", line 1568, in mtrand.RandomState.uniform (numpy/random/mtrand/mtrand.c:16695)
  File "mtrand.pyx", line 234, in mtrand.cont2_array_sc (numpy/random/mtrand/mtrand.c:3000)
ValueError: negative dimensions are not allowed

**Comment by redhat12345** [comment]
I have tried with both theano 0.8.1 and theano 0.9.0. Got the same error. I am not sure what happened ?

**Comment by wzell** [comment]
hallo redhat12345,

the Alexnet implementation is from https://github.com/heuritech/convnets-keras. There, you can find your issue: https://github.com/heuritech/convnets-keras/issues/18.

Seems that this issue has to do with the "image_dim_ordering" parameter in the keras.json file.

Please let me know if that helps.

**Comment by redhat12345** [comment]
By editing ~/.keras/keras.json file

{
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}
It worked for me. Thank you so much for your kind reply. By the way you did a great job.

**Comment by redhat12345** [comment]
It creates a lot of augmented images (100000) per dataset. Is there any effect of numbers of augmented images in accuracy?

**Comment by wzell** [comment]
Thank you :-).

The data augmentation is only for comparability reasons to other approaches that use data augmentation (Domain-adversarial neural networks, the mmd family of papers, DAN etc. and deep-CORAL).

I did not analyse the number of images on the accuracy. In the paper you can see that there are two approaches (mann and robust-mann in the code). One needs the augmented images (mann) and it is only for sake of comparability with other approaches that use data augmentation. The other approach (robust-mann) does not need the data augmentation. Please see the paper for details.

If you are not interested in running the full experiment (needs ~1 week), I suggest to uncomment everything that uses data augmentation (CNN network+mann) and just run the robust-mann implementation with only one repetition. This will need ~10min for the whole dataset. With increasing repetition number, the results should approach the table in the paper.

**Comment by wzell** [comment]
I close this issue since the error is solved and I change its name. Please open a new one if further errors occur.

**Comment by redhat12345** [comment]
Thank you so much. It would be really appreciable if you publish the commented version of the code which will give the results quickly. I am sorry that in close issue, I made a comment.

**Comment by wzell** [comment]
Done. Hope that helps.
