### ISSUE TITLE
CORAL Implementation

### ISSUE THREAD

**Issue by deep0learning** [wzell/mann#2]
At first I would like to thank you so much for your great work.

In your code, there is a script named **correlation_alignment.py**  . So if we want to get the result of CORAL method, what can we do? 

If we just change 
from models.correlation_alignment import CORALRegularizer  

in object_recognition.py  script, it would be ok? Please I am waiting your answer.

**Comment by wzell** [comment]
Hello deep0learning,
nice to see your interest in our project!

You corectly recognized, that we have to do the import
`from models.correlation_alignment import CORALRegularizer`
After that, we initialize the regularizer via
`coral = CORALRegularizer(l=1.0)# \lambda weighting as in original paper`
and we replace 'cmd' in every model initialization by 'coral', e.g. we use
`nn_coral_wc = MANN(TMP_FOLDER, n_features=256, activity_regularizer=coral, optimizer='adadelta')`

Please let us know if that works for you!

**Comment by deep0learning** [comment]
Thank you so much. I got it. Thanks again for your work.
